import React from 'react';
import { useTranslation } from 'react-i18next';
import '../styles/MainMenu.css';

const MainMenu = ({ onStartNewCase, onContinueCase, onSettings }) => {
  const { t } = useTranslation();

  return (
    <div className="main-menu">
      <div className="menu-container">
        <div className="menu-card">
          <div className="menu-icon">🕵️‍♂️</div>
          <h2>{t('app.title')}</h2>
          <p className="menu-description">
            Solve AI-generated mystery cases. Each case is unique!
          </p>
        </div>

        <div className="menu-buttons">
          <button 
            className="menu-button primary"
            onClick={onStartNewCase}
          >
            <span className="button-icon">🆕</span>
            <span className="button-text">{t('app.start')}</span>
            <span className="button-subtext">Start a new investigation</span>
          </button>

          <button 
            className="menu-button secondary"
            onClick={onContinueCase}
          >
            <span className="button-icon">📂</span>
            <span className="button-text">{t('app.continue')}</span>
            <span className="button-subtext">Continue saved case</span>
          </button>

          <button 
            className="menu-button tertiary"
            onClick={onSettings}
          >
            <span className="button-icon">⚙️</span>
            <span className="button-text">{t('app.settings')}</span>
            <span className="button-subtext">Game settings</span>
          </button>
        </div>

        <div className="menu-features">
          <div className="feature">
            <div className="feature-icon">🌍</div>
            <div className="feature-text">
              <h4>Global Cases</h4>
              <p>Investigate crimes from around the world</p>
            </div>
          </div>
          
          <div className="feature">
            <div className="feature-icon">🤖</div>
            <div className="feature-text">
              <h4>AI-Generated</h4>
              <p>Every case is unique and generated by AI</p>
            </div>
          </div>
          
          <div className="feature">
            <div className="feature-icon">💸</div>
            <div className="feature-text">
              <h4>Monetization Ready</h4>
              <p>Built for global revenue streams</p>
            </div>
          </div>
        </div>

        <div className="monetization-options">
          <h3>Premium Features</h3>
          <div className="premium-items">
            <div className="premium-item">
              <div className="premium-icon">💡</div>
              <div className="premium-details">
                <h4>Hint Packs</h4>
                <p>Get unstuck with smart hints</p>
                <button className="buy-button">$0.99</button>
              </div>
            </div>
            
            <div className="premium-item">
              <div className="premium-icon">⭐</div>
              <div className="premium-details">
                <h4>Premium Cases</h4>
                <p>Exclusive complex cases</p>
                <button className="buy-button">$2.99</button>
              </div>
            </div>
            
            <div className="premium-item">
              <div className="premium-icon">🚫</div>
              <div className="premium-details">
                <h4>Ad-Free Experience</h4>
                <p>Remove all advertisements</p>
                <button className="buy-button">$4.99/month</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MainMenu;